### ISSUE TITLE
Tables with 3 or more rows won't show the third line on layout

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/clade-monitoreo-wptheme#14]
![rows2](https://cloud.githubusercontent.com/assets/11841075/19355187/dd78ff14-913f-11e6-9b37-5d05c6d821d0.png)
![rows1](https://cloud.githubusercontent.com/assets/11841075/19355186/dd78bdec-913f-11e6-9f2c-30695933e912.png)

**Comment by miguelpeixe** [comment]
That doesn't look like the issue.

Make sure you mark only the parent category for the table row. It will automatically look for subcategories to include as subrow. If you select a subcategory it will interpret as main row (with no parent relationship).

**Comment by miguelpeixe** [comment]
Another useful observation, the subcategory support is not available for columns, only rows.

**Comment by bwstefano** [comment]
Didn't do anything but the problem is now solved.
