### ISSUE TITLE
Change plot line color

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/clade-monitoreo-wptheme#17]
In some cases, the user won't be able to distinguish graphic's columns from the plot line.
![plotline](https://cloud.githubusercontent.com/assets/11841075/19358786/9f94efec-914d-11e6-83b0-d4bf5e277c71.png)

**Comment by miguelpeixe** [comment]
fixed with 36315b48ce36b3542ec0758b45c8c2fc242ad4f6
