### ISSUE TITLE
Theme groups: add scatter chart support

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/clade-monitoreo-wptheme#22]
Please refer to "análisis cruzado", a subsection of "panorama regional" in the Excel study. It uses a scatter chart with straight lines and charts to combine different data from existing datasets. Is it possible to add this using our current technology?

**Comment by miguelpeixe** [comment]
Selection of type of chart to use is now available.

Options are `column`, `bar`, `line`, `spline`, `area`,  `areaspline`, `scatter`
