### ISSUE TITLE
Separate countries' analysis links from general analysis page

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/clade-monitoreo-wptheme#23]

**Comment by miguelpeixe** [comment]
what was the final decision on where to put this section?

**Comment by bwstefano** [comment]
Still to have a separated page. You were to check what could be done so it
wouldn't be a weird page with just some flags as links to click.

Em 5 de nov de 2016 2:57 PM, "Miguel Peixe" notifications@github.com
escreveu:

**Comment by miguelpeixe** [comment]
But what content should go alongside? The country list could be turned into a shortcode, so it can be flexible enough to be inserted in any page.

**Comment by bwstefano** [comment]
It hasn’t been decided by CLADE staff, but I like the idea of transforming it to a shortcode so they can decide what to do by themselves.

**Comment by miguelpeixe** [comment]
Shortcode `[country_list]` now available:

![image](https://cloud.githubusercontent.com/assets/820752/20068824/5225d722-a501-11e6-90b6-0c6262af47d4.png)

**Comment by miguelpeixe** [comment]
Country shortcode now supports title parameter. Example:

```
[country_list title="Analisis por pais"]
```

Does not display title if parameter is not used.
