### ISSUE TITLE
Add a field for some description above graphics

### ISSUE THREAD

**Issue by bwstefano** [ecodigital/clade-monitoreo-wptheme#25]
This should be a theme related description to be inserted in the yellow area of the image below
![theme_description](https://cloud.githubusercontent.com/assets/11841075/19947705/95cd57b0-a106-11e6-85af-9723a950fdfa.png)

**Comment by miguelpeixe** [comment]
This theme description is theme-wide, right? Not for each data collection associated or theme-group association.

**Comment by bwstefano** [comment]
Yes. So in the case of this screenshot, it would be a description for all "Disponibilidad de recursos por persona en edad escolar" data.
